port: 8080

story_path: "TheIntercept.ink"
save_path: {
  state: "TheIntercept.save",
  log: "log.json",
}

heartbeatInterval: 2000 #in ms
sessionTimeout: 1000 #in ms

routes: {
  pages: public,
  eventStream: /stream,
  updateLog: /update/log,
  updateChoices: /update/choices,
  getMetadata: /metadata,
  sendChoice: /choose,
}
