port: 8080

story_path: "story.ink"
save_path: {
  state: "save.json",
  log: "log.json",
}

ink_variables: {
  cast: "cast", #List contianing all roles in turn order
  turn: "turn", #Tag that tracks turn order
}

heartbeatInterval: 2000 #in ms
sessionTimeout: 60000 #in ms

routes: {
  pages: public,
  eventStream: /stream,
  updateLog: /update/log,
  updateChoices: /update/choices,
  getMetadata: /metadata,
  sendChoice: /choose,
}
