port: 8080

story_path: "TheIntercept.ink"
save_path: "TheIntercept.save"

heartbeatInterval: 2000 #in ms
sessionTimeout: 2000 #in ms

routes: {
  pages: public,
  eventStream: /stream,
  updateLog: /update/log,
  updateChoices: /update/choices,
  sendChoice: /choose,
}
